cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.pyenv"
matrix:
  include:
    - os: linux
      dist: trusty
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.5
    - os: osx
      osx_image: xcode7.3
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.5
install:
  - source .travis/install.sh
script:
  - .travis/run.sh
