language: python
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.pyenv"
matrix:
  include:
    - os: linux
      dist: trusty
      python: 3.5
    - os: osx
      language: objective-c
      env: PYENV_VERSION=3.5.2
install:
  - "./.travis/install.sh"
script:
  - python setup.py test
