language: python
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.pyenv"
matrix:
  include:
    - os: linux
      python: 3.5
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: 
            - g++-4.9
            - oracle-java8-installer
            - maven
    - os: osx
      language: objective-c
      env: TRAVIS_PYTHON_VERSION=3.5 
install:
  - .travis/install.sh
script:
  - .travis/script.sh
after_success:
  - .travis/after_success.sh
