language: python
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.pyenv"
addons:
  hosts:
    - srvgal102.deri.ie 140.203.155.240
matrix:
  include:
    - os: linux
      python: 3.5
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      services:
        - docker
    - os: osx
      language: objective-c
      env: TRAVIS_PYTHON_VERSION=3.5
      services:
        - docker
before_install:
  - .travis/before_install.sh
install:
  - .travis/install.sh
before_script:
  - .travis/before_script.sh
script:
  - .travis/script.sh
after_success:
  - .travis/after_success.sh
after_script:
  - .travis/after_script.sh
