name: indexer-test
channels:
  - ptorrestr
  - conda-forge
  - salford_systems
  - pkgw
dependencies:
  - python=3.5
  - setuptools
  - pyyaml
  - tqdm
  - requests
  - pexpect
  - t2db_objects >=0.7.6
  - hdtconnector >=0.2.2
  - pytest
