package:
  name: indexer
  version: {{ GIT_DESCRIBE_TAG }}
build:
  number: {{ GIT_DESCRIBE_NUMBER }}
source:
  path: ../
requirements:
  build:
    - python
    - setuptools
    - zlib
    - bzip2
    - requests
    - pyyaml
    - tqdm
    - pexpect
    - jsonrpclib-pelix
    - t2db_objects >=0.7.6
    - hdtconnector >=0.2.2
  run:
    - python
    - zlib
    - bzip2
    - requests
    - pyyaml
    - tqdm
    - pexpect
    - jsonrpclib-pelix
    - t2db_objects >=0.7.6
    - hdtconnector >=0.2.2
test:
  source_files:
    - etc
    - indexer/tests
  requires:
    - pytest
  commands:
    - pytest
about:
  home: https://github.com/ptorrestr/indexer
  license: GPLv3
