package:
  name: indexer
  version: 0.1.3
source:
  git_url: https://github.com/ptorrestr/indexer
  git_rev: 0.1.3
requirements:
  build:
    - python
    - setuptools
    - zlib
    - bzip2
    - hdtconnector
  run:
    - python
    - zlib
    - bzip2
    - hdtconnector
test:
  - python setup test

about:
  home: https://github/ptorrestr/indexer
  license: GPLv3
